### ISSUE TITLE
Code is not theme-agnostic

### ISSUE THREAD

**Issue by iosulfur** [mdo/wtf-forms#48]
I would like to use this repository, but I would be unable to do so without overwriting several styles, because the styles are coupled to a default theme. Has any thought been put to having a file of "theme-agnostic" code, and a file with the default theme? A minimal definition of theme-centric properties inlcude any assignment of color.

Example:

`wtf-forms.css`
```
.control {
  position: relative;
  display: inline-block;
  cursor: pointer;
}
```

`wtf-forms-theme.css`
```
.control {
  padding-left: 1.5rem;
  color: #555;
}
```

**Comment by Fequois** [comment]
Just adjust the default styles? Shouldn't be difficult to merge any future changes anyway. Decoupling in this case seems to provide unnecessary complexity rather than benefit in my opinion.

**Comment by iosulfur** [comment]
Okay. Will this repo still be maintained separately if the concept is
merged into Bootstrap?

**Comment by mdo** [comment]
Yeah, it'd be nice to decouple things more. This was more an exploration than anything else though and a cut-and-dry approach isn't all that useful or practical. For example, you might say `border` is presentation/theme, and I might say it's structural because it defines the boundaries of an element.

I'd suggest simply modifying the default styles for now.

@iosulfur Most likely, yes.
